Help the user fix the website
AAU-SW7-PSAAAB/energy-label-extension pull request #164
Opened 2024-11-27 14:49 UTC by atjn

- Provide more feedback that explains how to improve the score for each check.
- Include a link to the Sustainable Web Design entry for this check.
- Fix a few scores in the format plugin.

The user preference plugin is not updated in this PR because I am working on it in a separate PR, please ignore it for now.

2024-11-27 14:59 UTC, AlbertHald submitted a review, later dismissed
LTMG (jeg er yoda)

2024-11-28 11:51 UTC, AlbertHald approved these changes
GLTM

2024-11-28 11:51 UTC, merged

2024-11-28 11:55 UTC, BaBrixx requested changes

2024-11-28 11:55 UTC, BaBrixx commented on tests/e2e/querySelector.test.ts
>  	// Assert that the score is 38
```suggestion
	// Assert that the score is 50
```

2024-11-28 11:56 UTC, atjn commented on tests/e2e/querySelector.test.ts
>  	// Assert that the score is 38
tihi